name: Deploy UBVA IA - HOMOLOG

on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Checkout rep
        run: npm install -g typescript && git clone https://github.com/adrianoneco/ubvaia.git /tmp/ubvaia && git checkout homolog && npm install && tsc --noEmit && npm audit fix --force && rm -rf /tmp/ubvaia

      - name: Deploy via SSH (user + password)
        run: |
          sshpass -p "${{ secrets.HOMOLOG_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{
            secrets.HOMOLOG_SSH_USER }}@${{ secrets.HOMOLOG_SSH_HOST }} << 'EOF'

            cd /srv/sites/ubvaia-homolog
            git commit -m "check:commit ALL uncommited changes"

            echo "Pull do repositÃ³rio..."
            git checkout homolog && git pull origin homolog

            echo "Instalando dependÃªncias..."
            npm install -g typescript bun
            bun install --force

            echo "Corrigindo vunerabilidades de pacotes..."
            
            git checkout homolog && npm install
            tsc --noEmit && npm audit fix --force

            echo "Validando CÃ³digo"
            bun run check

            echo "Buildando..."
            bun run build

            echo "Reiniciando PM2..."
            chmod -R 777 /srv/sites/ubvaia-homolog
            pm2 restart ubvaia-homolog || pm2 start dist/index.js --name ubva-ia

            echo "ðŸš€ Deploy finalizado!"
          EOF
